### ISSUE TITLE
Wiki page on how to write designers

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DesignLibrary#11]
- write guide on documentation for a designer (Lily)
  - how to link designers to designs, using seealso
- how to add code to attributes
- how to add shiny arguments to attributes, and restrictions

**Comment by graemeblair** [comment]
Suggest this goes on Web site directly, not wiki?

**Comment by jaspercooper** [comment]
Good point. Was thinking we could still set up on the wiki for now as it's easy to preview and the markdown should be easy enough to port over to website when it's ready. It's helpful to have some guides up soon as a reference point while we build the library out.

**Comment by jaspercooper** [comment]
First version of vignette is finished
