### ISSUE TITLE
post treatment estimand wrong?

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DesignLibrary#134]
estimator_3 should have estimand_4 as its estimand, not estimand_3, right?

**Comment by jaspercooper** [comment]
Thanks -- thought this was fixed by Alex.. not sure how his changes got clobbered.

In any case, we've deprecated this designer for now.

**Comment by jaspercooper** [comment]
Oh I see that the website doesn't reflect this change though -- that's odd it was made days ago. @Nick-Rivera any idea why the website hasn't updated vignettes? Master branch of library has been compiling fine on travis for the past week or so.

**Comment by graemeblair** [comment]
The whole web site is broken because of https://github.com/DeclareDesign/fabricatr/issues/143

**Comment by Nick-Rivera** [comment]
There's a fix in the works so that one page doesn't hold the site hostage, but for now it's stuck.

**Comment by jaspercooper** [comment]
https://github.com/DeclareDesign/DesignLibrary/commit/5b68491cc49fc0dce152020f2b0db727de1f699f
