### ISSUE TITLE
Release boilerplate

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DesignLibrary#148]
- merge to master (with all vignettes deleted
- add release tag
Then:
- increment version
- vignettes back in

**Comment by graemeblair** [comment]
Hey -- if I understand what problem you're trying to address (vignettes kept out of CRAN release) no need to do this. You can add vignettes to .Rbuildignore and then they aren't built for CRAN but are included in the Web site. We've done with this the other packages.
