### ISSUE TITLE
Typo in DESCRIPTION

### ISSUE THREAD

**Issue by leeper** [DeclareDesign/DesignLibrary#151]
You have a duplicated "using the using the" in the DESCRIPTION "Description" field (only on the CRAN-release branch, not master).

I don't understand your branch system so didn't submit a PR as it wasn't clear which branch you would want changes against. Perhaps consider adding a `CONTRIBUTING.md` file to explain how to contribute to the package?

**Comment by jaspercooper** [comment]
Thanks @leeper I saw this this morning -- it crept in during a last minute edit during the submission process. We are working on a new version so this will be updated soon. 

Thanks for the suggestion on `CONTRIBUTING.md` it's a good idea

**Comment by jaspercooper** [comment]
Will be fixed in same-version update to CRAN per conversation with maintainers.
