### ISSUE TITLE
all "example designs" are broken

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DesignLibrary#190]
when you click a design, it downloads a file of garbage text

is this a design library issue or a web site issue?

**Comment by macartan** [comment]
should be an rda file?

**Comment by jaspercooper** [comment]
I wrote a script some time ago that takes all designers in the GH version of the library and saves their default design to the website as .rda files. 

@Nick-Rivera I believe you implemented it -- is it possible something is breaking due to the new travis setup?

**Comment by macartan** [comment]
I suspect that unsuspecting users will not expect an RDA file when they
click on  sample design
Any really anyone who could use an RDA file could just as easily do design
<- designer()
I suggest we remove that column from the library!

**Comment by jaspercooper** [comment]
Agreed!

**Comment by nfultz** [comment]
Check your http headers, it's probably being sent in text mode instead of binary.

**Comment by graemeblair** [comment]
IMHO it's a bit funny to trumpet the portability of the design object itself and not be able to download them from the design library, but do see the point that you can do designer()

@nfultz is probably right it's just the headers. this is on AWS S3 so I'm not sure it's going to be straightforward to fix this

**Comment by macartan** [comment]
I see the point. Bit of a contradiction.
Portability seems more of an issue though if it is a particular design and
not just an implementation of a designer.

**Comment by graemeblair** [comment]
let's drop it - I don't think it will be easy for users to see what to do with this file as noted above and that seems reason enough. @jaspercooper are you able to drop that column or do we need @Nick-Rivera? I think you'll have to email him if so.

**Comment by Nick-Rivera** [comment]
It's a little messy to remove. I'll make a branch with the column removed + the logic that creates the files

**Comment by Nick-Rivera** [comment]
OK I checked [the preview](https://5b90ca9fdd28ef532eed1c8b--thirsty-morse-aa29ed.netlify.com/library/) and everything looks good. I'm ready to merge if everyone thinks it's OK.

**Comment by jaspercooper** [comment]
Awesome, thanks so much nick. Do you mind removing the reference to example
designs in the Bullet point above the table too?

**Comment by Nick-Rivera** [comment]
Okie dokie it has been done. Let me know if everything looks good:
[Preview](https://5b9411bb792f8949f0adfb9b--thirsty-morse-aa29ed.netlify.com/library/)

**Comment by jaspercooper** [comment]
Looks great thanks so much for the quick action on this Nick.
