### ISSUE TITLE
broken on CRAN

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DesignLibrary#241]
Hi all - DesignLibrary is broken on CRAN now - some of the errors are here: https://cran.r-project.org/web/checks/check_results_DesignLibrary.html

Can I suggest someone take a look and prepare a new version to submit to CRAN?

**Comment by jaspercooper** [comment]
Sure. I'm pretty sure the problem results from the change in syntax in
set_diagnosands() in one of the DD patches, and that this has already been
fixed in the dev version. Will look into it over coming days.
