### ISSUE TITLE
rlang update is going to break things

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DesignLibrary#248]
@clarabicalho did some detective work and found there is a `{{` operator now... which I would suppose will mess with the way we're getting design code.
https://github.com/r-lib/rlang/pull/742/files

@nfultz any thoughts on what to do here would be greatly appreciated, if you have time.

**Comment by clarabicalho** [comment]
@nfultz can correct me but I don't think it affects the designer codes, just the functions written in tests.

**Comment by nfultz** [comment]
I believe the rlang `{{}}` only applies to function calls / invocations which internally use `enquos` on the argument.  There should be minimal/zero impact on designers-internals unless a lot of NSE has been added. I don't believe we were ever passing designers function bodies around as quosures, only as text.

**Comment by clarabicalho** [comment]
Doesn't DesignLibrary:::pred() use designer body as expression when source code is missing?

**Comment by jaspercooper** [comment]
That sounds right to me. Some of the designs do have quosures within `{{{` (e.g., https://github.com/DeclareDesign/DesignLibrary/blob/master/R/factorial_designer.R#L225), but we are never doing NSE on the function bodies themselves. 

Going to take a look at your PR now @clarabicalho THanks so much to both of you for the quick movement on this

**Comment by jaspercooper** [comment]
I think we're good here -- Please feel free to chime in if not. 

Thanks everyone.
