### ISSUE TITLE
Create overview of designers and designs

### ISSUE THREAD

**Issue by medinali** [DeclareDesign/DesignLibrary#30]
Create a function that lists all available designers and designs with corresponding citation and description

**Comment by medinali** [comment]
Function create_overview lists all current designers. Still need to include designs.

**Comment by jaspercooper** [comment]
If you want to check out the citation functionality I just pushed a citation to RD_designer (should eventually be a DD team citation, but just put in some boilerplate for now).

**Comment by jaspercooper** [comment]
bc727b6

**Comment by medinali** [comment]
overview will be produced with package markdown
