### ISSUE TITLE
Cleanup diagnosis for kable

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DesignLibrary#36]
@acoppock 

Current function is in design/R/helpers 
It essentially puts the ses in parentheses under the diagnosands and does rounding and lets you add names if you use the defaults. Looks nice after kable. 

* better to be part of diagnose_design; and produce default print out after diagnosis
* should be more reliable in figuring out whether bootsrapping was done or not
* default names need to be consistent with current names which is risky; better perhaps for each diagnosand to have a long form label that is then taken for this purpose

reshape_diagnosis <- function(diagnosis, 
                              digits = 2, 
                              col.names = NULL, 
                              default.names = c("Estimator", "Coef Name", "Estimand", "Bias", "RMSE",  "Power", "Coverage", "Mean(Estimate)", "sd(Estimate)", "Mean(se)", "Type S", "Mean(Estimand)")
                              ) {

**Comment by jaspercooper** [comment]
This is an issue for DD
