### ISSUE TITLE
error with simple_two_arm_designer

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DesignLibrary#68]
Hi all -- trying to use `simple_two_arm_designer()`, but getting an error after a clean install of master branch. I see:

```
> library(DesignLibrary)
> simple_two_arm_designer(N = 100)
Error in construct_design_code(simple_two_arm_designer, match.call.defaults()) : 
  could not find opening tag in simple_two_arm_designer
```

What am I doing wrong?

**Comment by jaspercooper** [comment]
It's an error that results from not having the source code kept when the CMD install command is run, and should be fixed in https://github.com/DeclareDesign/DesignLibrary/pull/63

Can you try installing from that branch and let me know how you get on? Should be merged soon.

**Comment by jaspercooper** [comment]
cf #50

**Comment by jaspercooper** [comment]
Sorry -- fixed in https://github.com/DeclareDesign/DesignLibrary/pull/61

**Comment by graemeblair** [comment]
Thanks #61 got it for me
